version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: app_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123456
    ports:
      - '3307:3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/content:/etc/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:80'
    links:
      - db

  apache:
    build: ./apache
    volumes:
      - ./apache/content:/var/www/html/
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - '8081:80'
    links:
      - db
      - nginx

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # environment:
    #   PMA_HOST: ${PMA_HOST}
    #   PMA_PORT: ${PMA_PORT}
    ports:
      - '8082:80'
    links:
      - db
